{"uuid": "34e53795-353e-4e9f-8963-1843f7d2fe12", "children": ["f655af13-079e-4a87-9029-991a010937b0"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/sunzilin/UI/src/tests/app_logininterface_test.py\", line 19, in driver\n    driver = u2.connect()  # 连接手机，若电脑只连接了一部手机，则不需要设备信息\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/__init__.py\", line 1870, in connect\n    return connect_usb(addr)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/__init__.py\", line 1911, in connect_usb\n    return Device(serial)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/__init__.py\", line 247, in __init__\n    wlan_ip = self.wlan_ip\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/__init__.py\", line 426, in wlan_ip\n    ip = self.http.get(\"/wlan/ip\").text.strip()\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/requests/sessions.py\", line 602, in get\n    return self.request(\"GET\", url, **kwargs)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/__init__.py\", line 213, in request\n    self.__client._prepare_atx_agent()\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/__init__.py\", line 299, in _prepare_atx_agent\n    self._setup_atx_agent()\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/__init__.py\", line 310, in _setup_atx_agent\n    _initer.install()\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/init.py\", line 368, in install\n    self._install_uiautomator_apks()\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/init.py\", line 327, in _install_uiautomator_apks\n    path = self.push_url(url, mode=0o644)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/decorator.py\", line 235, in fun\n    return caller(func, *(extras + args), **kw)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/retry/api.py\", line 73, in retry_decorator\n    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/retry/api.py\", line 33, in __retry_internal\n    return f()\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/init.py\", line 226, in push_url\n    path = mirror_download(url,\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/init.py\", line 104, in mirror_download\n    return cache_download(mirror_url,\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/uiautomator2/init.py\", line 72, in cache_download\n    r = requests.get(url, stream=True, headers=headers, timeout=None)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/requests/adapters.py\", line 644, in send\n    resp = conn.urlopen(\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 773, in urlopen\n    self._prepare_proxy(conn)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\", line 1042, in _prepare_proxy\n    conn.connect()\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/urllib3/connection.py\", line 790, in connect\n    sock_and_verified = _ssl_wrap_socket_and_match_hostname(\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/urllib3/connection.py\", line 969, in _ssl_wrap_socket_and_match_hostname\n    ssl_sock = ssl_wrap_socket(\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/urllib3/util/ssl_.py\", line 480, in ssl_wrap_socket\n    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)\n  File \"/Users/sunzilin/UI/venv/lib/python3.9/site-packages/urllib3/util/ssl_.py\", line 524, in _ssl_wrap_socket_impl\n    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py\", line 500, in wrap_socket\n    return self.sslsocket_class._create(\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py\", line 1040, in _create\n    self.do_handshake()\n  File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ssl.py\", line 1309, in do_handshake\n    self._sslobj.do_handshake()\n"}, "start": 1758864936929, "stop": 1758864955156}], "start": 1758864936928, "stop": 1758864955991}